### ISSUE TITLE
Analyse des tests en .NET

### ISSUE THREAD

**Issue by Evi-Raoul** [Canard-Ecarlate/Backend#79]
FAIRE l'analyse des méthodes à utiliser pour mettre en place la couverture de test en .NET

- [x] Analyse des tests unitaires
- [x] Analyse des tests d'intégration

**Comment by Vincent-Letourmy** [comment]
J'ai mis en place un nouveau projet de test, composé de deux répertoires principaux :  
- UnitTests : Tous les tests unitaires
- IntégrationTests : Tous les tests d'intégration et de bout en bout
