### ISSUE TITLE
Implémenter les tests sur la gestion des salles

### ISSUE THREAD

**Issue by Evi-Raoul** [Canard-Ecarlate/Backend#85]
⚠️ A faire après que #67 (Implémenter les API de gestion de salle) soit terminée

FAIRE les tests lié aux fonctionnalités liées à la gestion des salles
LA TACHE EST TERMINEE LORSQUE les fonctionnalités suivantes sont testées : 

- [x] create room
- [x] join room
- [x] leave room

**Comment by Vincent-Letourmy** [comment]
Tests unitaires ok, tests d'intégration pas fait
